/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "SuperVanish"

// The visibility engine lives in its own module so it can be consumed as a plain
// library, with no Bukkit plugin lifecycle attached. The root project is a thin
// SuperVanish plugin built on top of it.
include("library")
